name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'container/**'

# defaults:
#   run:
#     working-directory: ./container

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
 #      Load our code to the virtual machine.
 #      It is an official GitHub Action used to check out a repository so a workflow can access it.
       - uses: actions/checkout@v2
       - name: Install
         working-directory: ./container
         run: npm install

       - name: Build
         working-directory: ./container
         run: npm run build

 #     AWS service CLI actions
 #     https://github.com/chrislennon/action-aws-cli
       - uses: chrislennon/action-aws-cli@v1.1

 #     sync webpack dist with AWS bucket
       - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
